// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgNw0F8CNpb8_jpv5UrIZZ_ibz-E0Bghc',
    appId: '1:806721437199:web:66469e6f41f7a42dd1ad7a',
    messagingSenderId: '806721437199',
    projectId: 'chapri-chat-app-bb72a',
    authDomain: 'chapri-chat-app-bb72a.firebaseapp.com',
    storageBucket: 'chapri-chat-app-bb72a.firebasestorage.app',
    measurementId: 'G-2Q12DHG5M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbaoaNOzL4G76WQoxZQL2nXjXvvbPakSs',
    appId: '1:806721437199:android:726f4a097bc19c1ed1ad7a',
    messagingSenderId: '806721437199',
    projectId: 'chapri-chat-app-bb72a',
    storageBucket: 'chapri-chat-app-bb72a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtr9iD-IX54-xwIe-gwD-xibGP7Hyqck',
    appId: '1:806721437199:ios:c6a39573e2be2edfd1ad7a',
    messagingSenderId: '806721437199',
    projectId: 'chapri-chat-app-bb72a',
    storageBucket: 'chapri-chat-app-bb72a.firebasestorage.app',
    iosBundleId: 'com.example.chapri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQtr9iD-IX54-xwIe-gwD-xibGP7Hyqck',
    appId: '1:806721437199:ios:c6a39573e2be2edfd1ad7a',
    messagingSenderId: '806721437199',
    projectId: 'chapri-chat-app-bb72a',
    storageBucket: 'chapri-chat-app-bb72a.firebasestorage.app',
    iosBundleId: 'com.example.chapri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgNw0F8CNpb8_jpv5UrIZZ_ibz-E0Bghc',
    appId: '1:806721437199:web:d98fc154c85b0551d1ad7a',
    messagingSenderId: '806721437199',
    projectId: 'chapri-chat-app-bb72a',
    authDomain: 'chapri-chat-app-bb72a.firebaseapp.com',
    storageBucket: 'chapri-chat-app-bb72a.firebasestorage.app',
    measurementId: 'G-NT33M1C5VM',
  );
}
